<?php
// $Id: uc_weightquote.module,v 1.5.2.7 2009/02/13 22:01:15 islandusurper Exp $

/**
 * @file
 * Shipping quote module that defines a shipping rate for each product based on weight.
 */

/******************************************************************************
 * Drupal Hooks                                                               *
 ******************************************************************************/

/**
 * Implementation of hook_menu().
 */
function uc_weightquote_menu() {
  $items = array();

  $items['admin/store/settings/quotes/methods/weightquote'] = array(
    'title' => 'Weight quote',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_weightquote_admin_settings'),
    'access arguments' => array('configure quotes'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'uc_weightquote.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 *
 * Add a form element for the shipping rate of a product.
 *
 * @see uc_product_form()
 */
function uc_weightquote_form_alter(&$form, &$form_state, $form_id) {
  if (uc_product_is_product_form($form)) {
    $enabled = variable_get('uc_quote_enabled', array());
    $weight = variable_get('uc_quote_method_weight', array('weightquote' => 0));
    $form['shipping']['weightquote'] = array(
      '#type' => 'fieldset',
      '#title' => t('Shipping rate by weight'),
      '#collapsible' => TRUE,
      '#collapsed' => ($enabled['weightquote'] == FALSE),
      '#weight' => $weight['weightquote'],
    );

    $form['shipping']['weightquote']['weightquote'] = array(
      '#type' => 'textfield',
      '#title' => t('Shipping cost per !unit', array('!unit' => variable_get('uc_weight_unit', 'lb'))),
      '#description' => t('The amount per weight unit to add to the shipping cost for an item.<br />Example: to add $5 per pound, put 5 in here.'),
      '#default_value' => $form['#node']->weightquote,
      '#size' => 16,
      '#field_prefix' => variable_get('uc_sign_after_amount', FALSE) ? '' : variable_get('uc_currency_sign', '$'),
      '#field_suffix' => (variable_get('uc_sign_after_amount', FALSE) ? variable_get('uc_currency_sign', '$') : '') . t('/!unit', array('!unit' => variable_get('uc_weight_unit', 'lb'))),
    );
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function uc_weightquote_nodeapi(&$node, $op) {
  if (uc_product_is_product($node->type)) {
    switch ($op) {
      case 'insert':
      case 'update':
        if ($node->weightquote !== '') {
          if (!$node->revision) {
            db_query("DELETE FROM {uc_weightquote_products} WHERE vid = %d", $node->vid);
          }
          db_query("INSERT INTO {uc_weightquote_products} (vid, nid, rate) VALUES (%d, %d, %f)",
            $node->vid, $node->nid, $node->weightquote);
        }
      break;
      case 'load':
        $rate = db_result(db_query("SELECT rate FROM {uc_weightquote_products} WHERE vid = %d", $node->vid));
        if ($rate === FALSE || $rate < 0) {
          return array('weightquote' => variable_get('uc_weightquote_product_default', 0.00));
        }
        else {
          return array('weightquote' => $rate);
        }
      break;
      case 'delete':
        db_query("DELETE FROM {uc_weightquote_products} WHERE nid = %d", $node->nid);
      break;
      case 'delete revision':
        db_query("DELETE FROM {uc_weightquote_products} WHERE vid = %d", $node->vid);
      break;
    }
  }
}

/******************************************************************************
 * Conditional Actions Hooks                                                  *
 ******************************************************************************/

/**
 * Implementation of hook_ca_predicate().
 *
 * Connect the weightquote action and event.
 */
function uc_weightquote_ca_predicate() {
  $enabled = variable_get('uc_quote_enabled', array());

  $predicates = array(
    'uc_weightquote_get_quote' => array(
      '#title' => t('Shipping quote via product weight'),
      '#trigger' => 'get_quote_from_weightquote',
      '#class' => 'uc_weightquote',
      '#status' => $enabled['weightquote'],
      '#actions' => array(
        array(
          '#name' => 'uc_quote_action_get_quote',
          '#title' => t('Fetch a shipping quote'),
          '#argument_map' => array(
            'order' => 'order',
            'method' => 'method',
          ),
        ),
      ),
    ),
  );

  return $predicates;
}

/******************************************************************************
 * Ubercart Hooks                                                             *
 ******************************************************************************/

/**
 * Implementation of Ubercart's hook_shipping_method().
 */
function uc_weightquote_shipping_method() {
  $methods = array();

  $enabled = variable_get('uc_quote_enabled', array());
  $weight = variable_get('uc_quote_method_weight', array('weightquote' => 0));
  $methods['weightquote'] = array(
    'id' => 'weightquote',
    'module' => 'uc_weightquote',
    'title' => t('Weight rate per product'),
    'enabled' => $enabled['weightquote'],
    'quote' => array(
      'type' => 'order',
      'callback' => 'uc_weightquote_quote',
      'accessorials' => array(
        t('Shipping'),
      ),
    ),
    'weight' => $weight['weightquote'],
  );

  return $methods;
}

/******************************************************************************
 * Module Functions                                                           *
 ******************************************************************************/

/**
 * Standard callback to return a shipping rate via the weightquote method.
 *
 * @param $products
 *   The order's products.
 * @param $details
 *   Other order details including a shipping address.
 * @return
 *   A JSON object containing the shipping quote for the order.
 */
function uc_weightquote_quote($products, $details) {
  $rate = 0;
  foreach ($products as $product) {
    $node = node_load($product->nid);
    $rate += $node->weightquote * $product->qty * $product->weight * uc_weight_conversion($node->weight_units, variable_get('uc_weight_unit', 'lb'));
  }
  $rate += variable_get('uc_weightquote_base_rate', 0);

  $method = uc_weightquote_shipping_method();

  $quotes[] = array('rate' => $rate, 'format' => uc_currency_format($rate), 'option_label' => $method['weightquote']['quote']['accessorials'][0]);

  return $quotes;
}
