<?php
// $Id: uc_stock.module,v 1.12.2.11 2009/02/27 22:41:33 islandusurper Exp $

/**
 * @file
 * Allow ubercart products to have stock levels associated with their SKU
 *
 * uc_stock enables ubercart to manage stock for products. Store admins can set
 * the stock levels on a product edit page and a threshold for each SKU value
 * When that threshold is reached admins can be optionally notified about the
 * current stock level. Store admins can view all stock levels in the reports
 * section of Ubercart.
 *
 * Development sponsored by the Ubercart project.  http://www.ubercart.org
 */

require_once('uc_stock.ca.inc');

/******************************************************************************
 *  Hook Functions (Drupal)                                                   *
 ******************************************************************************/

/**
 * Implementation of hook_help().
 */
function uc_stock_help($path, $arg) {
  switch ($path) {
    case 'node/%/edit/uc-stock':
      return t('To keep track of stock for a particular product SKU, make sure it is marked as active and enter a stock value. When the stock level drops below the threshold value, you can be notified based on your stock settings.');
    case 'admin/store/reports/stock':
    case 'admin/store/reports/stock/threshold':
      return t('This is the list of product SKUs that are currently active. Stock levels below their threshold have highlighted rows. Toggle the checkbox below to alter which stock levels are shown.');
  }
}

/**
 * Implementation of hook_menu().
 */
function uc_stock_menu() {
  $items = array();

  $items['admin/store/settings/stock'] = array(
    'title' => 'Stock settings',
    'description' => 'View the stock settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_stock_settings_form'),
    'access arguments' => array('administer product stock'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uc_stock.admin.inc',
  );
  $items['admin/store/reports/stock'] = array(
    'title' => 'Stock reports',
    'description' => 'View reports for product stock.',
    'page callback' => 'uc_stock_report',
    'access arguments' => array('view reports'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'uc_stock.admin.inc',
  );
  $items['node/%node/edit/uc-stock'] = array(
    'title' => 'Stock',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_stock_edit_form', 1),
    'access arguments' => array('administer product stock'),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
    'file' => 'uc_stock.admin.inc',
  );
  return $items;
}

function uc_stock_perm() {
  return array('administer product stock');
}

function uc_stock_theme() {
  return array(
    'uc_stock_edit_form' => array(
      'arguments' => array('content' => NULL),
      'file' => 'uc_stock.admin.inc',
    ),
  );
}

/**
 * Implementation of hook_mail().
 */
function uc_stock_mail($key, &$message, $params) {
  switch ($key) {
    case 'threshold':
      $message['subject'] = $params['subject'];
      $message['body'] = $params['body'];
      break;
  }
}

/******************************************************************************
 * Ubercart Hooks                                                             *
 ******************************************************************************/

/**
 * Implementation of hook_token_list().
 */
function uc_stock_token_list($type = 'all') {
  if ($type == 'stock' || $type == 'ubercart' || $type == 'all') {
    $tokens['stock']['stock-level'] = t('The current stock level');
    $tokens['stock']['stock-model'] = t('The model or SKU of the stock level');
    $tokens['stock']['stock-threshold'] = t('The threshold or warning limit of the stock level');
  }

  return $tokens;
}

/**
 * Implementation of hook_token_values().
 */
function uc_stock_token_values($type, $object = NULL) {
  switch ($type) {
    case 'stock':
      $values['stock-level'] = $object->stock;
      $values['stock-model'] = $object->sku;
      $values['stock-threshold'] = $object->threshold;
      break;
  }

  return $values;
}

/**
 * Implementation of hook_uc_message().
 */
function uc_stock_uc_message() {
  $messages['uc_stock_threshold_notification_subject'] = t('[store-name]: Stock threshold limit reached');
  $messages['uc_stock_threshold_notification_message'] = t("This message has been sent to let you know that the stock level for the model [stock-model] has reached [stock-level]. There may not be enough units in stock to fulfill order #[order-link].");
  return $messages;
}


/******************************************************************************
 * Callback Functions, Forms, and Tables                                      *
 ******************************************************************************/


/******************************************************************************
 *  Module and Helper Functions                                               *
 ******************************************************************************/

/**
 * Adjust the product stock level by a set amount.
 *
 * @param $sku
 *   The product SKU of the stock level to adjust.
 * @param $qty
 *   The amount to add to or subtract from the stock level.
 */
function uc_stock_adjust($sku, $qty) {
  db_query("UPDATE {uc_product_stock} SET stock = stock + %d WHERE sku = '%s'", $qty, $sku);
}

/**
 * Get the stock level of a particular product SKU
 * @param $sku
 *   The Ubercart product SKU of the stock level to return.
 * @return:
 *   The associated stock level with the particular SKU or FALSE if not active.
 */
function uc_stock_level($sku) {
  return db_result(db_query("SELECT stock FROM {uc_product_stock} WHERE sku = '%s' AND active = 1", $sku));
}

/**
 * Emails administrator regarding any stock level thresholds hit.
 *
 * @param $order
 *   The order object that tripped the threshold limit.
 * @param $product
 *   The product object that is associated with the SKU.
 * @param $stock
 *   The stock level object that contains the stock level and SKU.
 * @return
 *   The result of drupal_mail().
 */
function _uc_stock_send_mail($order, $stock) {
  $token_filters = array('global' => NULL, 'order' => $order, 'stock' => $stock);
  $account = user_load(array('uid' => $order));

  $to = variable_get('uc_stock_threshold_notification_recipients', variable_get('uc_store_email', ini_get('sendmail_from')));
  $from = uc_store_email_from();

  $subject = variable_get('uc_stock_threshold_notification_subject', uc_get_message('uc_stock_threshold_notification_subject'));
  $subject = token_replace_multiple($subject, $token_filters);

  $body = variable_get('uc_stock_threshold_notification_message', uc_get_message('uc_stock_threshold_notification_message'));
  $body = token_replace_multiple($body, $token_filters);

  return drupal_mail('uc_stock', 'threshold', $to, user_preferred_language($account), array('body' => $body, 'subject' => $subject) , $from, TRUE);
}

/**
 * Implementation of hook_views_tables().
 */
function uc_stock_views_tables() {
  $tables['uc_product_stock'] = array(
    'name' => 'uc_product_stock',
    'join' => array(
      'left' => array(
        'table' => 'node',
        'field' => 'nid'
      ),
      'right' => array(
        'field' => 'nid',
      ),
    ),
    'fields' => array(
      'sku' => array(
        'name' => t('Stock: SKU'),
        'help' => t('The model or SKU of the stock level'),
        'sortable' => TRUE,
      ),
      'active' => array(
        'name' => t('Stock: Active'),
        'help' => t('Whether or not the stock level is currently being tracked'),
        'handler' => 'uc_stock_views_handler_active',
        'sortable' => TRUE,
      ),
      'stock' => array(
        'name' => t('Stock: Stock Level'),
        'help' => t('The current stock level'),
        'sortable' => TRUE,
      ),
      'threshold' => array(
        'name' => t('Stock: Threshold'),
        'help' => t('The threshold or warning limit of the stock level'),
        'sortable' => TRUE,
      ),
    ),
    'sorts' => array(
      'sku' => array(
        'name' => t('Stock: SKU'),
      ),
      'stock' => array(
        'name' => t('Stock: Stock Level'),
        'help' => t('The current stock level'),
      ),
      'threshold' => array(
        'name' => t('Stock: Threshold'),
        'help' => t('The threshold or warning limit of the stock level'),
      ),
    ),
    'filters' => array(
      'sku' => array(
        'name' => 'Stock: SKU',
        'operator' => 'views_handler_operator_like',
        'handler' => 'views_handler_filter_like',
        'help' => t('Filter the node based on stock SKU.'),
      ),
      'stock' => array(
        'name' => 'Stock: Stock Level',
        'operator' => 'views_handler_operator_gtlt',
        'help' => t('Filter the node based on stock level.'),
      ),
      'threshold' => array(
        'name' => 'Stock: Threshold',
        'operator' => 'views_handler_operator_gtlt',
        'help' => t('Filter the node based on threshold level.'),
      ),
      'is_active' => array(
        'name' => 'Stock: Is Active',
        'operator' => array('=' => 'Equals'),
        'list' => 'views_handler_operator_yesno',
        'list-type' => 'select',
        'handler' => 'uc_stock_views_handler_filter_is_active',
        'help' => t('Filter the data based on whether or not stock tracking is active for the SKU.'),
      ),
      'below_threshold' => array(
        'name' => 'Stock: Is Below Threshold',
        'operator' => array('=' => 'Equals'),
        'list' => 'views_handler_operator_yesno',
        'list-type' => 'select',
        'handler' => 'uc_stock_views_handler_filter_below_threshold',
        'help' => t('Filter the node based on whether it stock level is below the threshold for the SKU.'),
      ),
    ),
  );

  return $tables;
}

function uc_stock_views_handler_active($fieldinfo, $fielddata, $value, $data) {
  return $value ? t('Active') : t('Inactive');
}

function uc_stock_views_handler_filter_below_threshold($op, $filter, $filterinfo, &$query) {
  if ($op == 'handler') {
    if ($filter['value'] == 0) {
      $operator = '>=';
    }
    else {
      $operator = '<';
    }
    $query->add_where('uc_product_stock.stock  '. $operator .' uc_product_stock.threshold');
  }
}

function uc_stock_views_handler_filter_is_active($op, $filter, $filterinfo, &$query) {
  if ($op == 'handler') {
    if ($filter['value'] == 1) {
      $active = '1';
    }
    else {
      $active = '0';
    }
    $query->ensure_table('uc_product_stock');
    $query->add_where('uc_product_stock.active = '. $active);
  }
}

