<?php
// $Id: jquery_drag_drop.module,v 1.1 2009/01/17 23:43:46 ebizondrupalservices Exp $


/**
 * Implementation of hook_menu().
 */
function jquery_drag_drop_menu() {

  $items = array();

  $items['admin/settings/jquery_drag_drop'] = array(
    'title' => 'Jquery Drag Drop admin settings',
    'description' => 'Update settings for drag and drop using jQuery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jquery_drag_drop_admin'),
    'access arguments' => array('administrator content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Create administration form
 */
function jquery_drag_drop_admin(&$form_state, $form_id = '', $op = '') {

  $form['drag_drop_block1'] = array(
    '#type' => 'textfield',
    '#title' => t('Div Id of first Block Region'),
    '#default_value' => variable_get('drag_drop_block1', 'div#sidebar-left'),
    '#description' => t('Set the CSS Block Div Id. For example, if your page.tpl.php looks like <code>&lt;div class="sidebar" id="sidebar-left"&gt;&lt;?php print $left; ?&gt;&lt;/div&gt;, then enter div#sidebar-left, to be able to drag-drop on left side region in sidebar-left'),
  );



  $form['drag_drop_block2'] = array(
    '#type' => 'textfield',
    '#title' => t('Div Id of second Block Region'),
    '#default_value' => variable_get('drag_drop_block2', 'div#sidebar-right'),
    '#description' => t('Set the CSS 2nd Block Div Id. For example, if your page.tpl.php looks like <code>&lt;div class="sidebar" id="sidebar-right"&gt;&lt;?php print $right; ?&gt;&lt;/div&gt;, then enter div#sidebar-right, to be able to drag-drop on right side region in sidebar-right'),
  );
  $form['drag_drop_block3'] = array(
    '#type' => 'textfield',
    '#title' => t('Div Id of 3rd Block Region'),
    '#default_value' => variable_get('drag_drop_block3', ''),
    '#description' => t('Set the CSS Block Div Id. For example, if your page.tpl.php looks like <code>&lt;div class="sidebar" id="region1"&gt;&lt;?php print $region1; ?&gt;&lt;/div&gt;, then enter div#region1, to be able to drag-drop in region1'),
  );


  return system_settings_form($form);
}

function _jquery_drag_drop_css() {
  $css_file = drupal_get_path('module', 'jquery_drag_drop') .'/jquery_drag_drop.css';
  drupal_add_css($css_file);
}

function _jquery_drag_drop_js() {
  jquery_interface_add();
  $sidebar[1] = variable_get('drag_drop_block1', 'div#sidebar-left');
  $sidebar[2] = variable_get('drag_drop_block2', 'div#sidebar-right');
  $sidebar[3] = variable_get('drag_drop_block3', '');

  for ($i = 1; $i <= 3; $i++) {
    drupal_add_js(<<<EOT
$(document).ready(
  function () {
    $('$sidebar[$i]').Sortable(
      {
        accept : 'block',
        onchange : function (obj) {
                     serial = $.SortSerialize(obj[0].id);
                     //alert(serial.hash);
                   },
        fx:			200,
        opacity:		0.8
      }
    )
  }
);  
function serialize(s)
{
	serial = $.SortSerialize(s);
	//alert(serial.hash);
}
EOT
      , 'inline'
    );
  }
}

/**
 * Implementation of moduleName_init().
 *
 */
function jquery_drag_drop_init() {

  _jquery_drag_drop_css();
  _jquery_drag_drop_js();
}

